name: Check Release
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  check_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1
        with:
          python_version: "3.9.x"
      # Workaround for https://github.com/jupyter-server/jupyter_releaser/issues/529
      - name: Fix jupyter_releaser
        run: |
          set -eux
          pip install --upgrade 'git+https://github.com/yacchin1205/jupyter_releaser.git@fix/unexpected-npm-call'
      - name: Check Release
        # Workaround for https://github.com/jupyter-server/jupyter_releaser/issues/529
        uses: jupyter-server/jupyter_releaser/.github/actions/check-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version_spec: minor
      - name: Runner debug info
        if: always()
        run: |
          echo "Node version: $(node --version)"
          echo "NPM version: $(npm --version)"
          echo "jlpm version: $(jlpm --version)"
          echo "Yarn version: $(yarn --version)"
          echo "Python version: $(python --version)"
