name: Release

on:
  workflow_dispatch:
    inputs:
      version_spec:
        description: "New Version Specifier"
        default: "next"
        required: false
      branch:
        description: "The branch to target"
        required: false

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.branch }}
    - name: Install node
      uses: actions/setup-node@v1
      with:
       node-version: '16.x'
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        architecture: 'x64'


    - name: Setup pip cache
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: pip-3.8-${{ hashFiles('package.json') }}
        restore-keys: |
          pip-3.8-
          pip-

    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"
    - name: Setup yarn cache
      uses: actions/cache@v2
      id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          yarn-

    - name: Install dependencies
      run: python -m pip install -U jupyterlab~=4.0 check-manifest jupyterlab-translate
    - name: Build the extension
      run: |
        set -eux
        jlpm
        jlpm run eslint:check

        # Prepare .mo file
        jupyterlab-translate compile . rdm_binderhub_jlabextension -l ja_JP

        python -m pip install .

        jupyter server extension list 2>&1 | grep -ie "rdm_binderhub_jlabextension.*OK"

        jupyter labextension list 2>&1 | grep -ie "rdm-binderhub-jlabextension.*OK"
        python -m jupyterlab.browser_check

  draft_release:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}
      - name: Base Setup
        uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1
      - name: Check Release
        uses: jupyter-server/jupyter_releaser/.github/actions/check-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: true
          prerelease: false
          release_name: ${{ github.event.inputs.version_spec }}
          tag_name: ${{ github.event.inputs.branch }}
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: upload pip package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: .jupyter_releaser_checkout/dist/rdm_binderhub_jlabextension-${{ github.event.inputs.version_spec }}.tar.gz
          asset_name: rdm_binderhub_jlabextension-${{ github.event.inputs.version_spec }}.tar.gz
          asset_content_type: application/gzip
      - name: upload nodejs package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: .jupyter_releaser_checkout/dist/rdm-binderhub-jlabextension-${{ github.event.inputs.version_spec }}.tgz
          asset_name: rdm-binderhub-jlabextension-${{ github.event.inputs.version_spec }}.tgz
          asset_content_type: application/gzip
